services:
  ec2-control-app:
    build: .
    ports:
      - "3003:3000"
    environment:
      - AWS_REGION=$AWS_REGION
      - INSTANCE_ID=$INSTANCE_ID
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - PAGE_TITLE=$PAGE_TITLE
    restart: always      
